import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{position: 'fixed', top: '0px', left: '0px', 'width': '100%', 'height': '40px', 'backgroundColor': 'royalblue'}}>
          Menu-2
        </div>
        {children}
      </body>
    </html>
  )
}
